spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/${rootArtifactId}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    schema:
      - classpath:sql/schema.sql
    data:
      - classpath:sql/data.sql
    continue-on-error: true
    initialization-mode: always
    sql-script-encoding: utf-8
    hikari:
      maximumPoolSize: 10
      minimumIdle: 2
      idleTimeout: 600000
      connectionTimeout: 30000
      maxLifetime: 1800000
  redis:
    host: 127.0.0.1
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

app:
  package-version: 20200706
k3s:
  postfix:
bluetron:
  sdk:
    debug-enable: true
    enabled: true
    request-url: http://192.168.8.100
    request-port: 8080
    app-id: 3bdd16c94781442fb8a073fe236f0c2a
    app-secret: 927314860E0BEFF375782D984047D6E2
    app-version: 2.70.01.00-200911-C
    read-timeout: 30
    app-data:
      factory-model: app_template_network
    accept-language: zh-cn
    aksk-enable: false


